version: '2.0'

x-common-variables: &common-variables
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9907:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  api:
    build:
      dockerfile: Dockerfile
      context: "./back"
    depends_on:
      - mysql_db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - 3002:8080

  front:
    build:
      dockerfile: Dockerfile
      context: ./front
    ports :
      - 8082:80

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8003:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
